services:

  postgres:
    image: postgres:15-alpine
    container_name: fx-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=currency_conversion_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ${GLOBAL_NETWORK}

  mongodb:
    image: mongo:latest
    container_name: fx-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=fxcommanddb
    volumes:
      - mongodb-data:/data/db
    networks:
      - ${GLOBAL_NETWORK}

  redis:
    image: redis:7-alpine
    container_name: fx-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ${GLOBAL_NETWORK}
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres-data:
  redis-data:
  mongodb-data: